force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wuhan</fullName>
            </value>
            <value>
                <fullName>Xi&apos;an</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Building__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>China</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Building__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ConferenceRoom__c/ConferenceRoom__c.object-meta.xml
<CustomObject>
    <label>Conference Room</label>
    <nameField>
        <label>Conference Room Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConferenceRoom__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>MeetingRoom</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ConferenceRoom__c/fields/Facility__c.field-meta.xml
<CustomField>
    <fullName>Facility__c</fullName>
    <label>Facility</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Zoom视频</fullName>
            </value>
            <value>
                <fullName>白板</fullName>
            </value>
            <value>
                <fullName>空调</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConferenceRoom__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>32F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConferenceRoom__c/fields/RoomNo__c.field-meta.xml
<CustomField>
    <fullName>RoomNo__c</fullName>
    <label>Room No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConferenceRoomUpdateNameHandlerTest.cls
@isTest
private class ConferenceRoomUpdateNameHandlerTest {
    static testMethod void testUpdateConferenceRoomNameHandler() {

        Building__c building = new Building__c();
        building.Name = '保利国际中心';
        building.Country__c = 'China';
        // Ignore the building city changing case, builing city should be required and accurate while initing
        building.City__c = 'Wuhan';
        building.Location__c = '武汉市东湖新技术开发区关山大道332号保利·时代K18地块A栋保利国际中心20层2001号';
        insert building;

        ConferenceRoom__c conferenceRoom = new ConferenceRoom__c();
        // conferenceRoom.Name = '';
        conferenceRoom.Building__c = building.Id;
        conferenceRoom.Floor__c = '32F';
        conferenceRoom.RoomNo__c = 'N1';
        conferenceRoom.Facility__c = 'Zoom视频;';
        conferenceRoom.Capacity__c = 4;
        insert conferenceRoom;

        Boolean matchInsertConferenceRoomName = false;
        Boolean matchUpdateConferenceRoomName = false;
        for(ConferenceRoom__c room : [SELECT Name FROM ConferenceRoom__c]) {

            if(room.Name == 'Wuhan32F/N1') {

                matchInsertConferenceRoomName = true;
            }
        }
        System.assertEquals(true, matchInsertConferenceRoomName);

        conferenceRoom.RoomNo__c = 'N10';
        conferenceRoom.Facility__c = 'Zoom视频;空调;';
        conferenceRoom.Capacity__c = 6;
        update conferenceRoom;

        for(ConferenceRoom__c room : [SELECT Name FROM ConferenceRoom__c]) {

            if(room.Name == 'Wuhan32F/N10') {

                matchUpdateConferenceRoomName = true;
            }
        }
        System.assertEquals(true, matchUpdateConferenceRoomName);
    }
}