force-app/main/default/objects/Building__c/Building__c.object-meta.xml
<CustomObject>
    <label>Building</label>
    <nameField>
        <label>Building Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Building__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wuhan</fullName>
            </value>
            <value>
                <fullName>Xi&apos;an</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConferenceRoom__c/ConferenceRoom__c.object-meta.xml
<CustomObject>
    <label>Conference Room</label>
    <nameField>
        <label>Conference Room Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConferenceRoom__c/fields/Building__c.field-meta.xml
<CustomField>
    <fullName>Building__c</fullName>
    <label>Building</label>
    <referenceTo>Building__c</referenceTo>
    <relationshipName>MeetingRoom</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ConferenceRoom__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>32F</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConferenceRoom__c/fields/RoomNo__c.field-meta.xml
<CustomField>
    <fullName>RoomNo__c</fullName>
    <label>Room No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConferenceRoomUpdateNameHandler.cls
public with sharing class ConferenceRoomUpdateNameHandler implements Triggers.Handler {

    public void handle() {
        
        List<ConferenceRoom__c> conferenceRoomList = new List<ConferenceRoom__c>();
        if(Trigger.isInsert) {

            for(ConferenceRoom__c conferenceRoom : [SELECT Building__r.City__c,
                                                            Floor__c,
                                                            RoomNo__c
                                                    FROM ConferenceRoom__c
                                                    WHERE Id IN :Trigger.new]){

                ConferenceRoom__c cr = new ConferenceRoom__c();
                cr.Id = conferenceRoom.Id;
                // considering adding some validation rules to gurantee the data quality.City and floor should be accurate while initing.
                cr.Name = conferenceRoom.Building__r.City__c + conferenceRoom.Floor__c + '/' + conferenceRoom.RoomNo__c;
                conferenceRoomList.add(cr);
            }
        }
        if(Trigger.isUpdate) {

            Map<Id,ConferenceRoom__c> idConferenceMap = new Map<Id,ConferenceRoom__c>();
            for(ConferenceRoom__c conferenceRoom : ((List<ConferenceRoom__c>)Trigger.old)) {

                idConferenceMap.put(conferenceRoom.Id, conferenceRoom);
            }
            for(ConferenceRoom__c conferenceRoom : [SELECT Building__r.City__c,
                                                            Floor__c,
                                                            RoomNo__c
                                                    FROM ConferenceRoom__c
                                                    WHERE Id IN :Trigger.new]){
                if(idConferenceMap.containsKey(conferenceRoom.Id) &&
                    idConferenceMap.get(conferenceRoom.Id).RoomNo__c != conferenceRoom.RoomNo__c) {

                    ConferenceRoom__c cr = new ConferenceRoom__c();
                    cr.Id = conferenceRoom.Id;
                    // considering adding some validation rules to gurantee the data quality.City and floor should be accurate while initing.
                    cr.Name = conferenceRoom.Building__r.City__c + conferenceRoom.Floor__c + '/' + conferenceRoom.RoomNo__c;
                    conferenceRoomList.add(cr);
                }
            }
        }
        if(conferenceRoomList.size() > 0) {

            update conferenceRoomList;
        }
    }
}